CREATE TABLE rules (
    rulesid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_id INTEGER REFERENCES games(gamesid) ON DELETE CASCADE NOT NULL,
    rule_title TEXT,
    rule_description TEXT NOT NULL,
    assigned_user INTEGER REFERENCES users(usersid) ON DELETE CASCADE NOT NULL
);